import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import usuarios from './pages/api/usuarios'


export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch('http://localhost:3000/api/usuarios');
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } }
}

export default function Home({data}) {
     //data = data.rows;
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js + MySql</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
      <table border="0" cellPadding="5">
        <thead>
          <tr>
            <td>ID</td>
            <td>Login</td>
            <td>Nome</td>
            <td>E-mail</td>
          </tr>
          </thead>
          <tbody>
            {data.rows.map(function(record){
                return (<tr>
                          <td>{record.id}</td>
                          <td>{record.nome_usuario}</td>
                          <td>{record.nome}</td>
                          <td>{record.email}</td>
                        </tr>);
            })}
          </tbody>
      </table>
        
      </main>

      
    </div>
  )
}
